### ISSUE TITLE
Does not work after Github UI redesign

### ISSUE THREAD

**Issue by dimisjim** [staff0rd/github-follow-extension#10]
Please include these fixes and release it in the chrome store https://github.com/jeffstieler/github-follow-extension

Thanks

**Comment by staff0rd** [comment]
Heya @dimisjim, do you want to raise a Pull Request?

**Comment by dimisjim** [comment]
@staff0rd seems that github doesn't let me:

![image](https://user-images.githubusercontent.com/6890249/130930517-c0cffe5c-e838-4627-9ac9-10dd05dabc0e.png)


I also get permission denied when trying to do it via local cli:
```
ERROR: Permission to staff0rd/github-follow-extension.git denied to dimisjim.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by staff0rd** [comment]
Maybe this is because that repo is not your own.

I've made some changes directly to `master` and submitted  v1.0.13 of the extension to the Chrome Store. That said, the submission process has been updated and the form advised review can take weeks, so I'm unsure when the update will become available for download.

**Comment by dimisjim** [comment]
>Maybe this is because that repo is not your own.

you don't have to own a repo to be able to open a PR. See github's repo settings :wink: 

Thanks for the fix anyway :+1: 

**EDIT Aug 29:** Indeed, it works after the new version in the chrome store, thanks a lot!
