### ISSUE TITLE
Support for private repos

### ISSUE THREAD

**Issue by edenman** [staff0rd/github-follow-extension#2]
Currently the extension tries to look up the commit:

```
https://api.github.com/repos/myorg/myrepo/commits/abc1234
```

But the repo is private, so we just get this back:

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

How is auth handled for the github API calls?  Seems like this extension would need to use the [Scopes](https://developer.github.com/v3/oauth/#scopes) stuff?

**Comment by staff0rd** [comment]
Looks like [OAuth](https://developer.github.com/v3/oauth/) needs to be implemented for this.

**Comment by edenman** [comment]
Yeah, that's what I was afraid of :(

**Comment by staff0rd** [comment]
Actually it looks like it can be done with just an OAuth Token.  I'm implementing it now but there may be security concerns.

**Comment by staff0rd** [comment]
I added an options page where you can generate (github link) and enter a personal access key, which in turns allows the extension to work with private repositories.

From what I have read, Chrome does not encrypt this data.  The options page does not reveal a previously entered key, however, it is likely possible for someone with access to your machine to investigate Chrome's local storage and extract it.  For security reasons this is not ideal, and if anyone has a better idea on how this can be done please share.

**EDIT Nov 2016**

I looked into using GitHub's Application Authorization, however it seems due to the requirement that the client secret be packaged with the extension, this is not an option.

**Comment by edenman** [comment]
Wow, that's some quick turnaround, thanks!  Looks like options.js didn't get packaged, though:

<img width="1440" alt="screen shot 2016-02-29 at 10 55 51 pm" src="https://cloud.githubusercontent.com/assets/1063557/13420064/d00fc03e-df37-11e5-9b03-cba46b4da044.png">

**Comment by staff0rd** [comment]
fixed via 76dc982.  Webstore should update within 1 hour.

**Comment by edenman** [comment]
:pray:

**Comment by edenman** [comment]
Works great, thanks again!
