### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by nerijus** [staff0rd/github-follow-extension#6]
It seems it no longer works.

**Comment by jnyrup** [comment]
This seems to be due to rate limiting from GitHub?
I can get this to work be creating an OAuth token with no additional scopes.

**Comment by Amelia-Lopez** [comment]
I wonder if it's a regression from adding support for private repos. The request the extension is sending includes the header and value `Authorization: token` with no actual token when none is configured in the extension's options. GitHub returns a 401 Unauthorized as a result.

Like @jnyrup mentioned, when I add an OAuth token with no additional scopes (i.e. no checkboxes checked), the token gets filled in on the request header, the request is successful, and the history button begins showing up in the history page of files that have been moved.

As an aside, the extension doesn't seem to make a request at all when looking at a commit diff where files have been moved, so that doesn't seem to be working, at least not for me. Also, this was all tested on a public repo.

**Comment by staff0rd** [comment]
Hey guys, sorry for the delayed response, for some reason I was not notified of this issue - or I missed it.

I've updated the extension to reflect the current css selectors on the latest github pages - this has fixed both the broken history and commits feature.

@Mario-Lopez you were correct, there was also a regression due to the OAuth token - I've fixed that also so it will work when no OAuth token has been supplied.

Have published 1.0.7 to chrome store.  Let me know if any issues.
