### ISSUE TITLE
Trying to use on private repo: can't save the OAuth token

### ISSUE THREAD

**Issue by LoneAtom** [staff0rd/github-follow-extension#8]
Hi,

I just installed version 1.0.9 and the save button for the OAuth token does nothing on the Options page.

The Chrome inspection console shows this error message:
"Failed to load resource: net::ERR_FILE_NOT_FOUND   options.js:1"

Anything I can do on my side to fix the issue?

Thanks!

**Comment by staff0rd** [comment]
It seems since 75a39b607696cd8a8ef18b047f4b48f9054ccee6 for some reason I removed that file from the manifest.  This didn't break my unpacked version of the extension, but did break the `dist` version.

Fixed now in 0c2c00b392f2c1bd72095208e128182ea43d1bac, v1.0.10 is now on the chrome store.

Thanks for the report.
